import "swiper/css/bundle";

import Providers from "./providers";

import "react-lite-youtube-embed/dist/LiteYouTubeEmbed.css";
import "./globals.css";
export const metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      data-theme="light"
      lang="en"
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
