import Script from "next/script";
import { getServerSession } from "next-auth";

import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import Providers from "./providers";

import "./globals.css";
import "react-contexify/dist/ReactContexify.css";

export const metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html
      data-theme="light"
      lang="en"
    >
      <head>
        <Script src="https://unpkg.com/@johanaarstein/dotlottie-player@latest/dist/index.js" />
      </head>
      <body>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
