import { headers } from "next/headers";
import Script from "next/script";
import { Session } from "next-auth";

import Providers from "./providers";

import "./globals.css";
export const metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`${process.env.WEBSITE}/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(headers().get("cookie") ?? "");
  return (
    <html
      data-theme="light"
      lang="en"
    >
      <head>
        <Script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.js" />
      </head>
      <body>
        <Providers {...{ session }}>{children}</Providers>
      </body>
    </html>
  );
}
